// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry       = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Link");

function make(href, $staropt$star, children) {
  var className = $staropt$star ? $staropt$star[0] : "";
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return ReasonReact.createDomElement("a", {
                  className: className,
                  href: href,
                  onClick: Curry._1(self[/* handle */0], (function ($$event, _) {
                          $$event.preventDefault();
                          return ReasonReact.Router[/* push */0](href);
                        }))
                }, children);
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
